---
- hosts: al
  tasks: 
  - name: Sends the "src=/home/cty/BusSale/conf/application.conf" of the target host to the native "/data/backup/"
    fetch: 
      src: /home/cty/BusSale/conf/application.conf
      dest: /data/backup/
          
  - name: Sends the "src=/home/cty/BusSync/conf/application.conf" of the target host to the native "/data/backup/"
    fetch:
      src: /home/cty/BusSync/conf/application.conf
      dest: /data/backup/
          
  - name: Sends the "src=/etc/sysconfig/network-scripts/ifcfg-eth0" of the target host to the native "/data/backup/"
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "6"
    fetch:
      src: /etc/sysconfig/network-scripts/ifcfg-eth0 
      dest: /data/backup/
          
  - name: Sends the "src=/etc/sysconfig/network-scripts/ifcfg-eth1" of the target host to the native "/data/backup/"
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "6"
    fetch:
      src: /etc/sysconfig/network-scripts/ifcfg-eth1
      dest: /data/backup/
        
  - name: Sends the "src=/etc/sysconfig/network-scripts/ifcfg-enp1s0" of the target host to the native "/data/backup/"
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"
    fetch:
      src: /etc/sysconfig/network-scripts/ifcfg-enp1s0
      dest: /data/backup/
          
  - name: Sends the "src=/etc/sysconfig/network-scripts/ifcfg-enp2s0" of the target host to the native "/data/backup/"
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"
    fetch:
      src: /etc/sysconfig/network-scripts/ifcfg-enp2s0
      dest: /data/backup/
